# Generated by Django 4.2.20 on 2025-05-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_medication_medicalrecord_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='brand_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='dosage_form',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='generic_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='known_reactions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='pharm_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='route',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='substance_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
