repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-json
    -   id: detect-private-key
    -   id: debug-statements

-   repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
    -   id: black
        language_version: python3
        exclude: ^(frontend|node_modules|.*\b(migrations)\b.*$)

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black"]
        exclude: ^(frontend|node_modules|.*\b(migrations)\b.*$)

-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-django]
        exclude: '^.*\b(migrations)\b.*$|frontend|node_modules'

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy
        exclude: '^.*\b(migrations|tests)\b.*$|frontend|node_modules'
        additional_dependencies: [types-requests, django-stubs]

# Custom Django check hook
-   repo: local
    hooks:
    -   id: django-check
        name: django-check
        entry: python manage.py check
        language: system
        types: [python]
        pass_filenames: false
